language: java
dist: trusty
addons:
  sonarcloud:
    organization: dimitardsimeonov
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar
  - mvn cobertura:cobertura coveralls:report