package bg.softuni.shop_app.model.entity.enums;

public enum Location {
    SOFIA("София"),
    PLOVDIV("Пловдив"),
    VARNA("Варна"),
    BURGAS("Бургас"),
    RUSE("Русе"),
    STARA_ZAGORA("Стара Загора"),
    PLEVEN("Плевен"),
    DOBRICH("Добрич"),
    SLIVEN("Сливен"),
    SHUMEN("Шумен"),
    PERNIK("Перник"),
    PAZARDZHIK("Пазарджик"),
    YAMBOL("Ямбол"),
    HASKOVO("Хасково"),
    BLAGOEVGRAD("Благоевград"),
    VELIKO_TARNOVO("Велико Търново"),
    VRATZA("Враца"),
    GABROVO("Габрово"),
    ASENOVGRAD("Асеновград"),
    VIDIN("Видин"),
    KAZANLAK("Казанлък"),
    KARDJALI("Кърджали"),
    KUSTENDIL("Кюстендил"),
    MONTANA("Монтана"),
    TARGOVISHTE("Търговище"),
    DIMITROVGRAD("Димитровград"),
    SILISTRA("Силистра"),
    LOVECH("Ловеч"),
    DUPNITZA("Дупница"),
    RAZGRAD("Разград"),
    GORNA_ORYAHOVITZA("Горна Оряховица"),
    SVISHTOV("Свищов"),
    PETRICH("Петрич"),
    SMOLYAN("Смолян"),
    SANDANSKI("Сандански"),
    SAMOKOV("Самоков"),
    VELINGRAD("Велинград"),
    SEVLIEVO("Севлиево"),
    LOM("Лом"),
    NOVA_ZAGORA("Нова Загора"),
    KARLOVO("Карлово"),
    AITOS("Айтос"),
    TROYAN("Троян"),
    BOTEVGRAD("Ботевград"),
    HARMANLI("Харманли"),
    PESHTERA("Пещера"),
    GOCE_DELCHEV("Гоце Делчев"),
    SVILENGRAD("Свиленград"),
    KARNOBAT("Карнобат"),
    PANAGYURISHTE("Панагюрище"),
    CHIRPAN("Чирпан"),
    POPOVO("Попово"),
    RAKOVSKI("Раковски"),
    RADOIR("Радомир"),
    PARVOMAY("Първомай"),
    NOVI_ISKAR("Нови Искър"),
    POMORIE("Поморие"),
    NESEBAR("Несебър"),
    CHERVEN_BRYAG("Червен Бряг"),
    KOZLODUY("Козлодуй"),
    IHTIMAN("Ихтиман"),
    NOVI_PAZAR("Нови Пазар"),
    BERKOVITZA("Берковица"),
    RADNEVO("Раднево"),
    PROVADIYA("Провадия"),
    RAZLOG("Разлог"),
    BALCHIK("Балчик"),
    BYALA_SLATINA("Бяла Слатина"),
    KAVARNA("Каварна"),
    KOSTINBROD("Костинброд"),
    BANKYA("Банкя"),
    STABMOIYSKI("Стамболийски"),
    ETROPOLE("Етрополе"),
    KNEZHA("Кнежа"),
    LEVSKI("Левски"),
    PAVLIKENI("Павликени"),
    MEZDRA("Мездра"),
    ELHOVO("Елхово"),
    TETEVEN("Тетевен"),
    LUKOVIT("Луковит"),
    TUTRAKAN("Тутракан"),
    TRYAVNA("Трявна"),
    DEVNYA("Девня"),
    SREDETZ("Средец"),
    OMURTAG("Омуртаг"),
    SOPOT("Сопот"),
    ISPERIH("Исперих"),
    VELIKI_PRESLAV("Велики Преслав"),
    BYALA("Бяла"),
    RAKITOVO("Ракитово"),
    GALABOVO("Гълъбово"),
    KRICHIM("Кричим"),
    LYASKOVETZ("Лясковец"),
    SEPTEMVRI("Септември"),
    MOMCHILGRAD("Момчилград"),
    BANSKO("Банско"),
    BELENE("Белене"),
    AKSAKOVO("Аксаково"),
    BELOSLAV("Белослав"),
    SVOGE("Своге"),
    DRYANOVO("Дряново"),
    LUBIMETZ("Любимец"),
    KUBRAT("Кубрат"),
    PIRDOP("Пирдоп"),
    ELIN_PELIN("Елин Пелин"),
    SIMITLI("Симитли"),
    SLIVNITZA("Сливница"),
    ZLATOGRAD("Златоград"),
    HISARYA("Хисаря"),
    DULOVO("Дулово"),
    DOLNI_CHIFLIK("Долни Чифлик"),
    SIMEONOVGRAD("Симеоновград"),
    GENERAL_TOSHEVO("Генерал Тошево"),
    TERVEL("Тервел"),
    KOSTENETZ("Костенец"),
    DEVIN("Девин"),
    MADAN("Мадан"),
    STRALDZA("Стралджа"),
    TZAREVO("Царево"),
    VARSHETZ("Вършец"),
    TVARDITZA("Твърдица"),
    KUKLEN("Куклен"),
    BOBOV_DOL("Бобов Дол"),
    KOTEL("Котел"),
    SAEDINENIE("Съединение"),
    ELENA("Елена"),
    ORYAHOVO("Оряхово"),
    YAKORUDA("Якоруда"),
    BOJURISHTE("Божурище"),
    TOPOLOVGRAD("Тополовград"),
    BELOGRADCHIK("Белоградчик"),
    STRAJITZA("Стражица"),
    KAMENA("Камено"),
    CHEPELARE("Чепеларе"),
    SOZOPOL("Созопол"),
    PERUHTITZA("Перущица"),
    SUVOROVO("Суворово"),
    ZLATITZA("Златица"),
    KRUMOVGRAD("Крумовград"),
    DOLNA_BANYA("Долна Баня"),
    DALGODOL("Дългопол"),
    VETOVO("Ветово"),
    POLSKI_TRAMBESH("Полски Тръмбеш"),
    TRASTENIK("Тръстеник"),
    KAINARE("Койнаре"),
    DOLNI_DABNIK("Долни Дъбник"),
    SLAVYANOVO("Славяново"),
    GODECH("Годеч"),
    PRAVETZ("Правец"),
    IGNATIEVO("Игнатиево"),
    KOSTANDVO("Костандово"),
    BRATZIGOVO("Брацигово"),
    DVE_MOGILI("Две Могили"),
    STRELCHA("Стрелча"),
    NEDELINO("Неделино"),
    SVETI_VLAS("Свети Влас"),
    SAPAREVA_BANYA("Сапарева Ббаня"),
    BREZNIK("Брезник"),
    SMYADOVO("Смядово"),
    ARDINO("Ардино"),
    DEBELETZ("Дебелец"),
    NIKOPOL("Никопол"),
    SHIVACHEVO("Шивачево"),
    BELOVO("Белово"),
    TZAR_KALOYAN("Цар Калоян"),
    MARTEN("Мартен"),
    IVAYLOVGRAD("Ивайловград"),
    KRESNA("Кресна"),
    VARBITZA("Върбица"),
    RUDOZEM("Рудозем"),
    VALCHEDRAM("Вълчедръм"),
    PRIMORSKO("Приморско"),
    GLODZEVO("Глоджево"),
    LETNITZA("Летница"),
    MAGLIZH("Мъглиж"),
    ISKAR("Искър"),
    SHABLA("Шабла"),
    GULYANTZI("Гулянци"),
    DOLNA_MITROPOLIYA("Долна Митрополия"),
    KRAN("Крън"),
    VALCHI_DOL("Вълчи Дол"),
    SLIVO_POLE("Сливо Поле"),
    BANYA("Баня"),
    DRAGOMAN("Драгоман"),
    SUNGURLARE("Сунгурларе"),
    BATAK("Батак"),
    DZEBEL("Джебел"),
    ZAVET("Завет"),
    KRIVODOL("Криводол"),
    MIZIYA("Мизия"),
    BELITZA("Белица"),
    KASPICHAN("Каспичан"),
    KULA("Кула"),
    NIKOLAEVO("Николаево"),
    VETREN("Ветрен"),
    GURKOVO("Гурково"),
    ROMAN("Роман"),
    KALOFER("Калофер"),
    KABLESHKOVO("Каблешково"),
    APRILTZI("Априлци"),
    BUHOVO("Бухово"),
    DOLNA_ORYAHOVITZA("Долна Оряховица"),
    PAVEL_BANYA("Павел Баня"),
    YABLANITZA("Ябланица"),
    RILA("Рила"),
    OPAKA("Опака"),
    UGARCHIN("Угърчин"),
    ZLATARITZA("Златарица"),
    HADZIDIMOVO("Хаджидимово"),
    DOBRINISHTE("Добринище"),
    OBZOR("Обзор"),
    BYALA_CHERKVA("Бяла Черква"),
    DUNAVTZI("Дунавци"),
    BREGOVO("Брегово"),
    TRAN("Трън"),
    SADOVO("Садово"),
    KALIFAREVO("Килифарево"),
    LAKI("Лъки"),
    MALKO_TARNOVO("Малко Търново"),
    DOSPAT("Доспат"),
    KOPRIVSHTITZA("Копривщица"),
    KOCHERINOVO("Кочериново"),
    LOZNITZA("Лозница"),
    BOROVO("Борово"),
    CHENOMORETZ("Черноморец"),
    BATANOVTZI("Батановци"),
    PORDIM("Пордим"),
    AHELOY("Ахелой"),
    SUHINDOL("Сухиндол"),
    BALGAROVO("Българово"),
    BREZOVO("Брезово"),
    GLAVNITZA("Главиница"),
    KAOLINOVO("Каолиново"),
    CHIPROVTZI("Чипровци"),
    MERICHLERI("Меричлери"),
    ZEMEN("Земен"),
    PLACHKOVTZI("Плачковци"),
    KERMEN("Кермен"),
    MOMIN_PROHOD("Момин Проход"),
    ALFATAR("Алфатар"),
    GRAMADA("Грамада"),
    SENOVO("Сеново"),
    BOICHINOVTZI("Бойчиновци"),
    ANTONOVO("Антоново"),
    AHTOPOL("Ахтопол"),
    BOBOSHEVO("Бобошево"),
    SHIPKA("Шипка"),
    BOLYAROVO("Болярово"),
    DIMOVO("Димово"),
    BRUSARTZI("Брусарци"),
    KITEN("Китен"),
    KLISURA("Клисура"),
    PLISKA("Плиска"),
    MADZAROVO("Маджарово"),
    MELNIK("Мелник");

    private String displayName;

    Location(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }
}